---
title: Unknown
format:
  pdf:
    keep-tex: true  
    toc: false
header-includes: |
  \usepackage{hyperref}
  \addtokomafont{disposition}{\rmfamily}
  \usepackage{siunitx}
  \newcommand{\aax}{$\mathrm{AA}$}
  \newcommand{\Aamphi}{$A_{\mathrm{amphi}}$}
  \newcommand{\Ahypo}{$A_{\mathrm{hypo}}$}
  \newcommand{\agcurve}{$A \textendash g_\text{sw}$}
  \newcommand{\ca}{$C_\mathrm{a}$}
  \newcommand{\caequals}[1]{$C_\mathrm{a} = \qty{#1}{\micro\mol\raiseto{-1}\mol}$}
  \newcommand{\cabetween}[2]{#1 < $C_\mathrm{a} < \qty{#2}{\micro\mol\raiseto{-1}\mol}$}
  \newcommand{\gsw}{$g_\text{sw}$}
  \newcommand{\ppfd}{$\mathrm{PPFD}$}
  \newcommand{\ppfdequals}[1]{$\mathrm{PPFD} = \qty{#1}{\micro\mol\raiseto{-2}\meter\raiseto{-1}\second}$}
  \newcommand{\rh}{$\mathrm{RH}$}
  \newcommand{\rhequals}[1]{$\mathrm{RH} = #1\%$}
  \newcommand{\tleafequals}[1]{$T_\mathrm{leaf} = \qty{#1}{\degreeCelsius}$}
mainfont: Times New Roman
bibliography: solanum-aa.bib
csl: https://www.zotero.org/styles/science
---

```{r load-objects, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
library(brms)
library(cowplot)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(knitr)
library(lubridate)
library(magrittr)
library(readr)
library(stringr)
library(tibble)
library(tidyr)

theme_set(theme_cowplot())

source("../r/functions.R")

aa_args = read_rds("../objects/aa_args1.rds")
aa_stats = read_rds("../objects/aa_stats.rds")
# sort list by name
aa_stats = aa_stats[order(names(aa_stats))]

plant_info = read_rds("../data/plant-info.rds")

accession_info = read_rds("../data/accession-info.rds") |>
  dplyr::select(species, accession)

rh_curves = read_rds("../data/trimmed_rh_curves.rds")

stomata = read_rds("../data/stomata.rds")

fit_aa2 = read_rds("../objects/fit_aa2.rds")
```

```{r fit_aa2, results = 'asis', echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}
#| label: tbl-fit_aa2
#| tbl-cap: "Parameter estimates and 95% confidence intervals (CIs) from the posterior distribution of the selected model with leaf mass per area (LMA) as potential mediator variable. Models potentially include fixed, random, and distributional effects of growth light intensity (shade and sun), measurement light intensity (low and high), $\\log \\mathrm{LMA}$, and their interactions on amphistomy advantage ($\\mathrm{AA}$). The distributional effects refer to the effect of factors on residual variation in $\\mathrm{AA}$, denoted $\\sigma$, on a log-link scale. LMA can also be affected by growth light intensity and population. For phylogenetically structured random effects, we report the estimated standard deviation (SD)."

make_brms_summary_table = function(fit,
                                   ci_level = 0.95,
                                   digits = 2) {
  # Get posterior summary
  summ = posterior_summary(fit, prob = c((1 - ci_level) / 2, 1 - (1 - ci_level) / 2))
  summ_df = as.data.frame(summ)
  summ_df$param = rownames(summ_df)
  colnames(summ_df) = c("Estimate", "Est.Error", "CI_low", "CI_high", "Parameter")
  
  # Classify parameters
  summ_df = summ_df |>
    mutate(
      Type = case_when(
        grepl("^b_", Parameter) &
          !grepl("sigma|Intercept", Parameter) ~ "fixed effects",
        grepl("^b_(aa|llma)_Intercept$", Parameter) ~ "fixed effects",
        grepl("^b_", Parameter) &
          grepl("sigma", Parameter) ~ "distributional parameters",
        grepl("^sd_", Parameter) ~ "random effect SDs",
        TRUE ~ "Other",
      ),
      resp = case_when(
        str_detect(Parameter, "_aa_") ~ "aa",
        str_detect(Parameter, "_llma_") ~ "lma",
        TRUE ~ NA_character_
      )
    )
  
  # Clean parameter names
  summ_df <- summ_df %>%
    mutate(Parameter = case_when(
      
      # AA
      Parameter == "b_aa_Intercept" ~ "$\\mathrm{AA}$ intercept (shade, low light)",
      Parameter == "b_aa_light_treatmenthigh" ~ "effect of sun on $\\mathrm{AA}$",
      Parameter == "b_aa_light_intensity2000" ~ "effect of high light on $\\mathrm{AA}$",
      Parameter == "b_aa_light_treatmenthigh:light_intensity2000" ~ "effect of sun $\\times$ high light interaction on $\\mathrm{AA}$",
      Parameter == "b_sigma_aa_Intercept" ~ "$\\log \\sigma$ intercept (shade, low light)",
      Parameter == "b_sigma_aa_light_treatmenthigh" ~ "effect of sun on $\\log \\sigma$",
      Parameter == "b_sigma_aa_light_intensity2000" ~ "effect of high light on $\\log \\sigma$",
      Parameter == "sd_acc__aa_Intercept" ~ "$\\mathrm{AA}$ among populations",
      Parameter == "sd_acc__aa_light_treatmenthigh" ~ "effect of sun on $\\mathrm{AA}$ among populations",
      Parameter == "sd_acc__aa_light_intensity2000" ~ "effect of high light on $\\mathrm{AA}$ among populations",
      Parameter == "sd_acc__aa_light_treatmenthigh:light_intensity2000" ~ "effect of sun $\\times$ high light interaction on $\\mathrm{AA}$ among populations",
      
      # LMA
      Parameter == "b_llma_Intercept" ~ "$\\log \\mathrm{LMA}$ intercept (shade)",
      Parameter == "b_llma_light_treatmenthigh" ~ "effect of sun on $\\log \\mathrm{LMA}$",
      Parameter == "b_sigma_llma_Intercept" ~ "$\\log \\sigma$ intercept (shade)",
      Parameter == "b_sigma_llma_light_treatmenthigh" ~ "effect of sun on $\\log \\sigma$",
      Parameter == "sd_acc__llma_Intercept" ~ "$\\log \\mathrm{LMA}$ among populations",
      Parameter == "sd_acc__llma_light_treatmenthigh" ~ "effect of sun on $\\log \\mathrm{LMA}$ among populations"
    ))
  
  # Select and format
  summ_df |>
    filter(Type != "Other") |>
    mutate(across(c(Estimate, CI_low, CI_high), ~ round(., digits))) |>
    mutate(`Estimate [95% CI]` = paste0(Estimate, " [", CI_low, ", ", CI_high, "]")) |>
    select(resp, Type, Parameter, `Estimate [95% CI]`) |>
    arrange(resp,
            match(
      Type,
      c(
        "fixed effects",
        "distributional parameters",
        "random effect SDs"
      )
    )) |>
    as_tibble()
}

summary_tbl = make_brms_summary_table(fit_aa2)

tbl_aa_fixed = summary_tbl |> filter(Type == "fixed effects", resp == "aa") |> select(-Type)
tbl_aa_dist  = summary_tbl |> filter(Type == "distributional parameters", resp == "aa") |> select(-Type)
tbl_aa_rand  = summary_tbl |> filter(Type == "random effect SDs", resp == "aa") |> select(-Type)
tbl_lma_fixed = summary_tbl |> filter(Type == "fixed effects", resp == "lma") |> select(-Type)
tbl_lma_rand  = summary_tbl |> filter(Type == "random effect SDs", resp == "lma") |> select(-Type)

bind_rows(tbl_aa_fixed, tbl_aa_dist, tbl_aa_rand, tbl_lma_fixed, tbl_lma_rand) |>
  select(-resp) |>
  kable(
    col.names = c("Parameter", "Estimate [95\\% CI]"),
    booktabs = TRUE,
    format = "latex",
    escape = FALSE
  ) |>
  kable_styling(latex_options = c("striped")) |>
  pack_rows("Response: $\\mathrm{AA}$", 1, nrow(tbl_aa_fixed) + nrow(tbl_aa_dist) + nrow(tbl_aa_rand), escape = FALSE) |>
  pack_rows("~~Fixed effects", 1, nrow(tbl_aa_fixed), escape = FALSE, bold = FALSE, italic = TRUE) |>
  pack_rows("~~Distributional parameters",
            nrow(tbl_aa_fixed) + 1,
            nrow(tbl_aa_fixed) + nrow(tbl_aa_dist), escape = FALSE, bold = FALSE, italic = TRUE) |>
  pack_rows(
    "~~Random effect SDs",
    nrow(tbl_aa_fixed) + nrow(tbl_aa_dist) + 1,
    nrow(tbl_aa_fixed) + nrow(tbl_aa_dist) + nrow(tbl_aa_rand), escape = FALSE, bold = FALSE, italic = TRUE
  ) |>
    pack_rows("Response: $\\log~\\\\mathrm{LMA}$", nrow(tbl_aa_fixed) + nrow(tbl_aa_dist) + nrow(tbl_aa_rand) + 1, nrow(tbl_aa_fixed) + nrow(tbl_aa_dist) + nrow(tbl_aa_rand) + nrow(tbl_lma_fixed) + nrow(tbl_lma_rand), escape = FALSE) |>
  pack_rows("~~Fixed effects", nrow(tbl_aa_fixed) + nrow(tbl_aa_dist) + nrow(tbl_aa_rand) + 1, nrow(tbl_aa_fixed) + nrow(tbl_aa_dist) + nrow(tbl_aa_rand) + nrow(tbl_lma_fixed), escape = FALSE, bold = FALSE, italic = TRUE) |>
 pack_rows(
    "~~Random effect SDs",
    nrow(tbl_aa_fixed) + nrow(tbl_aa_dist) + nrow(tbl_aa_rand) + nrow(tbl_lma_fixed) + 1,
    nrow(tbl_aa_fixed) + nrow(tbl_aa_dist) + nrow(tbl_aa_rand) + nrow(tbl_lma_fixed) + nrow(tbl_lma_rand), escape = FALSE, bold = FALSE, italic = TRUE
  ) |>
  column_spec(1, width = "4.5in") |>
  column_spec(2, width = "2in")

```